# Generated by Django 3.2.5 on 2021-07-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='problemPartiallySolved',
            new_name='problems_Partially_Solved',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='problemsSolved',
            new_name='problems_Solved',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='attemped',
            new_name='questions_attemped',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='partiallySolved',
            new_name='questions_partiallySolved',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='solved',
            new_name='questions_solved',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='sampleTc',
            new_name='sample_Tc',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='totalTC',
            new_name='total_Tc',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='inputGiven',
            new_name='input_Given',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='outputGen',
            new_name='output_Generated',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='dateTime',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='memoryLimit',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='timeLimit',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='testCasesPassed',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='userId',
        ),
        migrations.AddField(
            model_name='customuser',
            name='submissions',
            field=models.ManyToManyField(to='api.Submission'),
        ),
        migrations.AddField(
            model_name='problem',
            name='created_At',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='memory_Limit',
            field=models.IntegerField(blank=True, default=5120, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='time_Limit',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='submission_Date_Time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='test_Cases_Passed',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='total_Test_Cases',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='code',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(default='Queued', max_length=30),
        ),
        migrations.DeleteModel(
            name='DateTime',
        ),
    ]
