# Generated by Django 3.2.5 on 2021-07-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='input_Given',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='output_Generated',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='test_Cases_Passed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='total_Test_Cases',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
