# Generated by Django 3.2.5 on 2021-07-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210713_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='submissions',
            field=models.ManyToManyField(blank=True, null=True, to='api.Submission'),
        ),
    ]
