# Generated by Django 3.2.5 on 2021-07-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210712_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='partiallySolved',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='problemPartiallySolved',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='problemsSolved',
            field=models.TextField(blank=True, null=True),
        ),
    ]
