# Generated by Django 3.2.5 on 2021-07-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customuser_submissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='submissions',
            field=models.ManyToManyField(blank=True, to='api.Submission'),
        ),
    ]
