# Generated by Django 3.2.5 on 2021-07-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_customuser_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='memoryLimit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='timeLimit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
